services:
  broker1:
    build:
      context: ./java
    command: 
      - /opt/kafka/bin/kafka-server-start.sh 
      - /config/broker1.properties
    volumes:
      - ./files:/files
      - ./config:/config
      - ./data/broker1:/data
    depends_on:
      - quorum1
  broker2:
    build:
      context: ./java
    command: 
      - /opt/kafka/bin/kafka-server-start.sh 
      - /config/broker2.properties


    volumes:
      - ./files:/files
      - ./config:/config
      - ./data/broker2:/data
  broker3:
    build:
      context: ./java
    command: 
      - /opt/kafka/bin/kafka-server-start.sh 
      - /config/broker3.properties
    volumes:
      - ./files:/files
      - ./config:/config
      - ./data/broker3:/data

  quorum1:
    build:
      context: ./java
    command: 
      - /opt/kafka/bin/kafka-server-start.sh 
      - /config/quorum1.properties
    volumes:
      - ./files:/files
      - ./config:/config
      - ./data/quorum1:/data
